### PR TITLE
If Harpy not found new version or http request or etc... he just call new method

### PR DESCRIPTION
**Pull request by MeGaPk**

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Thanks for the PR. I'll look into this tonight.

**Comment by ArtSabintsev** [comment]
I looked into this PR. 

This is the second time someone has requested this feature in four years.

My question is **Why?**

Why would you want to know this information?

Thanks!

**Comment by MeGaPk** [comment]
I just show example, how i use:
```
- (void)sessionCheckMessage:(BOOL)result Answer:(NSDictionary *)answer {
    if (result) {
        [self.navigation changeToOrder];
    } else {
        [[Harpy sharedInstance] setPresentingViewController:[UIApplication sharedApplication].keyWindow.rootViewController];
        [[Harpy sharedInstance] setDelegate:self];
        [[Harpy sharedInstance] setForceLanguageLocalization:[NSBundle getCurrentLanguageCode]];
        [[Harpy sharedInstance] checkVersionDaily];
    }
    [self.socket disableSocket];
}

- (void)harpyUserDidLaunchAppStore {
    [self.navigation changeToFilters];
}

- (void)harpyUserDidSkipVersion {
    [self.navigation changeToFilters];
}

- (void)harpyUserDidCancel {
    [self.navigation changeToFilters];
}

- (void)harpyVersionCheckExecutedWithoutResults {
    [self.navigation changeToFilters];
}

````
self.navigation changeTo* < just change screen 


if i try show this alert in Main screen, i have race condition
If user click "change screen after 3 second" and after 1 second i see alert, screen not changed.

**Comment by ArtSabintsev** [comment]
Ah, so the race condition speaks to the bigger issue here.

What I would do is let your app load completely, and then and only then, would I show Harpy. 

Would that fix the issue on your end?

**Comment by MeGaPk** [comment]
yes, i solved this problem by my fix. Now i user cannot press any button on during "checking new version"

**Comment by ArtSabintsev** [comment]
But your fix wouldn't be necessary if you waited to show Harpy until every loads, right?

Regardless, closing this PR as I will not adding this feature.

**Pull request closed without merging**
