### PR TITLE
Translations: lv, ee

### PR DESCRIPTION
**Pull request by jaroslavas**
Latvian and Estonian translations

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
WOW, you speak a lot of languages! :)

I'll accept this PR tomorrow morning.

**Comment by ArtSabintsev** [comment]
Didn't have time this weekend, but I'll have time either tonight or tomorrow night. Thanks!

**Comment by ArtSabintsev** [comment]
Can you do me a favor and merge all your branches to your master branch? I want to checkout your entire repo on one branch so that I can play with it before accepting the PR.

Thanks!

**Comment by jaroslavas** [comment]
OK, I've merged everything into my master branch.

**Comment by ArtSabintsev** [comment]
I don't see it merged on the web. Did you push to origin/master?

**Comment by jaroslavas** [comment]
Hmm.. that's strange, I just browsed files on my [master branch ](https://github.com/jaroslavas/Harpy) and translations are there. Maybe I should make another pull request directly from my master branch?

**Comment by ArtSabintsev** [comment]
Hmm, odd, when I downloaded that branch, I didn't see the stuff in there. I'll try again when I'm at my computer.

**Comment by ArtSabintsev** [comment]
Done - thanks!

**Pull request merged**
