### PR TITLE
Urdu localization added

### PR DESCRIPTION
**Pull request by RajChanchal**
Urdu language is spoken in Pakistan and India.

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Thanks! Will test and merge it in the next 24 hours. I'll add it to Siren as well.

**Comment by ArtSabintsev** [comment]
The tests failed: https://dashboard.buddybuild.com/apps/58c4d37980c4290100790f8c/build/593c07e2cd3eb300016312fe

Looks like you forgot to add the localization the the Harpy.bundle file.

**Comment by ArtSabintsev** [comment]
Closing this PR since there's been no response.

**Comment by RajChanchal** [comment]
HI @ArtSabintsev , sorry I have added the file now. Check my new PR please.

**Pull request closed without merging**
