### PR TITLE
Issue with updating 3digit versions to 2digit

### PR DESCRIPTION
**Pull request by asxasxasx**
For example, 1.2.1 -> 1.3 crash resolved

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Thanks for the PR. I'll look soon. 

Did you also solve the situation where 3 digit updates to 4? and 4 digits updates to 3?

**Comment by ArtSabintsev** [comment]
Also, why would a developer ever switch version numbering systems. 

It seems kind of backwards to not just add the extra 0?

Then again, I think it's strange when people use 2 or 4 version numbering systems. Everyone should be using sem-ver...

**Comment by asxasxasx** [comment]
4 digit to 3 situation also solved. May be some developers don't like zeroes :)

**Comment by ArtSabintsev** [comment]
Apparently, Apple is enforcing 3-digit versioning:

https://github.com/Carthage/Carthage/issues/859#issuecomment-150114125

https://developer.apple.com/library/prerelease/ios/technotes/tn2420/_index.html#//apple_ref/doc/uid/DTS40016603-CH1-WATCHKIT_APPS_AND_APPS_WITH_SUB_FRAMEWORKS

Therefore, I am closing this PR.

**Pull request closed without merging**
