### PR TITLE
Adding Brazilian Portuguese localization and correcting European Portuguese

### PR DESCRIPTION
**Pull request by ipedro**
Adding the Brazilian Portuguese localization as pt, and renaming the European variant to pt-PT as per [Apple Docs](https://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html#//apple_ref/doc/uid/10000171i-CH5-SW3).

>The language ID for scripts or dialects uses subtags, as in pt-PT where pt is the code for Portuguese and PT is the code for Portugal. For example, use pt as the language ID for Portuguese as it is used in Brazil and pt-PT as the language ID for Portuguese as it is used in Portugal. The Other submenu (at the bottom of the list) contains more languages and dialects.

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Thanks for the PR. I'll merge it here and in Siren in the next 24 hours.

**Comment by ArtSabintsev** [comment]
Also, @ipedro, I see you made a lot of spacing/tabbing changes. This may be a pain-in-the-ass, but can you please revert all of your spacing changes by reforking this repo, and then changing/adding *only* the localization changes?

Thanks.

**Comment by ipedro** [comment]
That's weird... might have been Xcode

Sure, no problem

**Comment by ArtSabintsev** [comment]
Thanks!

**Pull request closed without merging**
