### PR TITLE
Incorrect title

### PR DESCRIPTION
**Pull request by wbison**
Only first word should be cap'ed

### CODE REVIEW

**Comment by wbison** [comment]
First pull request (and what a monumental one) - sorry if I messed up.

**Comment by ArtSabintsev** [comment]
no problem! Fix the tests, too! :)

**Comment by wbison** [comment]
hmm - the new commit was automagically added to the existing pr? I have to study this PR stuff.

Have I just started my career as Open Source Developer?

**Comment by ArtSabintsev** [comment]
Yes you have! Thanks for your contribution!

**Comment by ArtSabintsev** [comment]
Added this fix to the Swift version as well: https://github.com/ArtSabintsev/Siren/releases/tag/3.1.7

**Pull request merged**
