### PR TITLE
Portuguese (brazil) locale fixes

### PR DESCRIPTION
**Pull request by lucianocn**

### CODE REVIEW

**Comment by lucianocn** [comment]
I made some corrections to Portuguese (Brazil) locale ;)

The first is important because it is a grammatical mistake.
The second is an improvement.

**Comment by ArtSabintsev** [comment]
Thanks! I'll look at these in the evening.

**Comment by ArtSabintsev** [comment]
Been a bit busy with life - will try to get to this this week.

**Comment by ArtSabintsev** [comment]
Will do it tonight. Sorry for the delay!

**Pull request merged**
