### PR TITLE
Fix implicitly self retain warnings

### PR DESCRIPTION
**Pull request by kkostritsynax**

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Not seeing any retain warning sin Xcode 9.2. Not sure what this is about, so closing the PR due to lack of info.

**Comment by kkostritsynax** [comment]
If you add your project as pod in another project, then install pods with cocoapods 1.4.0 you will see these warnings.

**Comment by ArtSabintsev** [comment]
Will attempt to do this in the morning.

**Comment by ArtSabintsev** [comment]
By the way, is it in a Swift or Objc project?

**Comment by kkostritsynax** [comment]
ObjC project.

**Pull request closed without merging**
